### ISSUE TITLE
deployment fails if NetworkManager is not installed

### ISSUE THREAD

**Issue by asheplyakov** [altlinuxteam/ansible-samba#8]
TASK [samba : disble resolv.conf management by NM] *************************************************************************************************************************
fatal: [cl0]: FAILED! => {"changed": false, "msg": "Destination /etc/NetworkManager/NetworkManager.conf does not exist !", "rc": 257}
fatal: [cl1]: FAILED! => {"changed": false, "msg": "Destination /etc/NetworkManager/NetworkManager.conf does not exist !", "rc": 257}
	to retry, use: --limit @/home/asheplyakov/infra/samba-local.retry

**Comment by omgbebebe** [comment]
Which OS did you used? Currently this playbook support only ALTLinux. For clients deployment the ALTWorktation or KWorkstation assumed. Client deployment on ALT Server is not supported because the stable verison is lack of needed packages at now.

**Comment by asheplyakov** [comment]
I use the official ALTLinux p8 cloud image: http://nightly.altlinux.org/p8/release/alt-p8-cloud-20180612-x86_64.img.xz

> Currently this playbook support only ALTLinux.

It's pretty clear, and it would fail much earlier with another distro (due to apt_rpm, etc).

> For clients deployment the ALTWorktation or KWorkstation assumed.

This assumption is sort of strange. Joining VMs/server running ALTLinux to AD domain is perfectly sensible thing (say, to get your web app/database/etc authenticate its users with AD).

Also the task in question just tries to prevent NetworkManager from fiddling with /etc/resolv.conf, so it's basically no-op when NetworkManager is not installed.
